dist: xenial
language: python
python:
  - "3.6"
  - "3.7"

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n dev -c rdkit python=$TRAVIS_PYTHON_VERSION rdkit flake8 mypy pytest
  - source activate dev
  - conda install -c conda-forge jug codecov pytest-cov
  - pip install -e .

script:
  - pytest -v --cov=jugc/ --cov-report=
  - flake8
  - mypy ./jugc

after_success:
  - codecov
  - sphinx-apidoc -f -o docs/source/apis jugc
  - cd docs
  - make html

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: false
  on:
    branch: master
  github-token: $GITHUB_TOKEN
  local-dir: docs/build/html
  committer-from-gh: true

# This variable is generated and added by travis cli
env:
  global:
    secure: ENCRYPT_GITHUB_TOKEN
